exports.seed = (knex, Promise) => {
  return knex('grants').insert([
    // General Maori and Pacific grants
    { id: 1, name: 'Norman Kirk Memorial Scholarship', description: 'Available to full-time Māori undergraduate students studying at a recognised New Zealand tertiary institute.', grant_link: 'http://maorieducation.org.nz/undergraduate-scholarships-for-maori/', conditions: '', amount: 500 },
    { id: 2, name: 'Pacific Education Foundation Scholarships (PEF)', description: 'Pacific Education Foundation (PEF) Scholarships are open to Pasifika students enrolled in tertiary study in New Zealand.', grant_link: 'https://www.education.govt.nz/further-education/information-for-students/scholarships/pacific-education-foundation-scholarships-pef/', conditions: '', amount: 950 },
    // Technical grant
    { id: 3, name: 'Rose Hellaby Bursaries Scholarship', description: 'Available to Māori undergraduate students studying in the scientific, mathematical or technical fields.', grant_link: 'http://maorieducation.org.nz/undergraduate-scholarships-for-maori/', conditions: '', amount: 1000 },
    // Grants based on school attendance/NCEA
    { id: 4, name: 'Roy Watling Mitchell Bursaries Scholarship', description: 'Available to first-year Māori undergraduate students who attended secondary school as a Year 13 student in 2017.', grant_link: 'http://maorieducation.org.nz/undergraduate-scholarships-for-maori/', conditions: '', amount: 1000 },
    { id: 5, name: 'Sir Apirana Ngata Memorial Scholarship', description: 'Available to a full-time Māori undergraduate student studying at a recognised New Zealand tertiary institute, who attended Ngata Memorial College as a Year 13 student in 2017.', grant_link: 'http://maorieducation.org.nz/undergraduate-scholarships-for-maori/', conditions: '', amount: 1000 },
    // Grant based on heritage
    { id: 6, name: 'Sister Annie Henry Scholarship', description: 'The Sister Annie Henry Trust was established in 1972 to assist in the education or training of any direct descendants of Reverend John Laughton, or students of Tūhoe descent.', grant_link: 'http://maorieducation.org.nz/undergraduate-scholarships-for-maori/', conditions: 'Condition 6', amount: 700 },
    // General Grant
    { id: 7, name: 'Tī Maru Māori Trust Scholarship', description: 'Available to full-time Māori undergraduate students enrolled in their final year of study at a recognised New Zealand tertiary institute.', grant_link: 'http://maorieducation.org.nz/undergraduate-scholarships-for-maori/', conditions: '', amount: 5000 },
    // Grant based on characteristics and Heritage
    { id: 8, name: 'Ngārimu VC and 28th (Māori) Battalion Memorial Scholarships', description: 'The Ngārimu VC and 28th (Māori) Battalion Memorial Scholarship Fund Board is looking for exceptional applicants of Māori descent who are undertaking tertiary study in 2018 and who possess characteristics that are considered consistent with those of the members of the 28th Māori Battalion.', grant_link: 'http://www.education.govt.nz/further-education/information-for-students/scholarships/ngarimu-vc-and-28th-maori-battalion-memorial-scholarships/', conditions: '', amount: 10000 },
    // Digital Design, Arts
    { id: 9, name: 'Māori Emerging Talent Scholarship', description: 'These scholarships will cover the tuition fees for the entire Digital Creativity foundation programme, which cover the fees for both the New Zealand Certificate in Arts and Design and the New Zealand Certificate in Digital Media and Design (that, combined, make up the Digital Creativity foundation programme).', grant_link: 'https://www.mediadesignschool.com/scholarships/m%C4%81ori-emerging-talent-scholarship', conditions: '', amount: 9000 },
    { id: 10, name: 'Pacific Emerging Talent Scholarship', description: 'These scholarships will cover the tuition fees for the entire Digital Creativity foundation programme, which cover the fees for both the New Zealand Certificate in Arts and Design and the New Zealand Certificate in Digital Media and Design (that, combined, make up the Digital Creativity foundation programme).', grant_link: 'https://www.mediadesignschool.com/scholarships/pacific-emerging-talent-scholarship', conditions: '', amount: 9000 },
    // Female Art and Programming Grants
    { id: 11, name: 'Girls in Games Scholarship', description: 'The Girls in Games scholarship will give one female Game Artist and one female Game Programmer $2,000 to put towards their first year of undergraduate tuition fees at Media Design School.', grant_link: 'https://www.mediadesignschool.com/scholarships/girls-in-games', conditions: '', amount: 2000 },
    // Developer/Digital Design Grants
    { id: 12, name: 'Unity Games Scholarship', description: 'This scholarship will offer one aspiring developer the opportunity to study game development with the number one ranked 3D animation, visual effects and game school in the Asia Pacific region by contributing $2000 towards their first year of tuition.', grant_link: 'https://www.mediadesignschool.com/scholarships/unity-games-scholarship', conditions: '', amount: 2000 },
    { id: 13, name: 'Academic Excellence Scholarship', description: 'This Academic Excellence Scholarship will give a student with exceptional academic potential in digital design $2,000 to put towards their first year of undergraduate degree-level tuition fees with the Media Design School.', grant_link: 'https://www.mediadesignschool.com/scholarships/academic-excellence-scholarships', conditions: '', amount: 2000 },
    { id: 14, name: 'Māori Academic Excellence Scholarships', description: 'The Māori Academic Excellence scholarships provide a Maori student with exceptional academic potential in digital design a 50% discount on year 1 and 50% discount on year 2 the tuition fees of their chosen programme of study at the Media Design School.', grant_link: 'https://www.mediadesignschool.com/scholarships/m%C4%81ori-academic-excellence-scholarships', conditions: '', amount: 1 },
    { id: 15, name: 'Pacific Academic Excellence Scholarship', description: 'The Pacific Academic Excellence scholarships provide a Pacifica student with exceptional academic potential in digital design a 50% discount on year 1 and 50% discount on year 2 the tuition fees of their chosen programme of study at the Media Design School.', grant_link: 'https://www.mediadesignschool.com/scholarships/pacific-academic-excellence-scholarships', conditions: '', amount: 1 },
    // Dev Academy Specific Grants
    { id: 16, name: 'Te Uru Rangi', description: 'In conjunction with Te Puni Kōkiri and MBIE, Dev Academy is proud to announce 42 scholarships for Māori students. ', grant_link: 'https://devacademy.co.nz/te-uru-rangi/', conditions: '', amount: 7000 },
    { id: 17, name: 'Diversity Scholarship', description: 'This $500 scholarship is for people under-represented in the technology workforce, including anyone who belongs to an ethnic group under-represented in tech (e.g. Māori, Samoan, Tongan)', grant_link: 'https://devacademy.co.nz/course-details/', conditions: '', amount: 500 },
    // Music Grant
    { id: 18, name: 'New Zealand/Aotearoa Music Scholarship', description: 'Each year, up to two New Zealand/Aotearoa Music Scholarships enable young musicians to undertake study or gain further musical ex', grant_link: 'http://www.creativenz.govt.nz/find-funding/funds/new-zealand-aotearoa-music-scholarships', conditions: '', amount: 8000 },
    // Schooling based Grant
    { id: 19, name: 'AUT New Horizons Scholarships (Decile 1 – 4 Auckland Region Schools)', description: '', grant_link: 'https://www.aut.ac.nz/study-at-aut/fees-scholarships-and-finance/scholarships/scholarships-and-awards/detailpage?detailCode=501060&sessionID=3480386&sourceIP=&X_FORWARDED_FOR=', conditions: '', amount: 6500 },
    // Art Grant
    { id: 20, name: 'Maori Education Trust: Frances Irwin Hunt Art Scholarships', description: 'The purpose of the scholarship programme is to provide support for Māori students to pursue and achieve success in programmes of study and training.', grant_link: 'https://www.aut.ac.nz/study-at-aut/fees-scholarships-and-finance/scholarships/scholarships-and-awards/detailpage?detailCode=804031&sessionID=26622934&sourceIP=&X_FORWARDED_FOR=', conditions: 'Condition 20', amount: 3500 },
    // Student Excellence Grant
    { id: 21, name: 'Maori Education Trust: Roy Watling Mitchell Prestigious Professions Scholarship', description: 'Available to a Māori graduate with a record of academic excellence. Applicants must provide a reference from their supervisor/s regarding their research.', grant_link: 'https://www.aut.ac.nz/study-at-aut/fees-scholarships-and-finance/scholarships/scholarships-and-awards/detailpage?detailCode=800342&sessionID=26622934&sourceIP=&X_FORWARDED_FOR=', conditions: '', amount: 5000 },
    { id: 22, name: 'Te Herenga Waka Marae Whānau House Scholarship', description: 'The purpose of this scholarship is to encourage first year Māori students to academically and culturally achieve at Victoria University of Wellington.', grant_link: 'https://www.victoria.ac.nz/explore/study-areas/music/study?subject=sonic-arts-and-music-technology', conditions: '', amount: 7698 },
    // NZ and Pacific Bond Grant
    { id: 23, name: 'New Zealand Pacific Scholarships', description: 'The New Zealand Pacific Scholarship recognises the very close personal, cultural and economic ties that New Zealand enjoys with Pacific countries. A particular focus of the scheme is to increase the number of young students and high academic achievers studying in New Zealand and to build a new generation of Pacific Leadership with strong links to New Zealand.', grant_link: 'https://www.victoria.ac.nz/study/student-finance/scholarships/find-scholarship/scholarship-detail?detailCode=803308', conditions: '', amount: 1 },
    // Music specific grants
    { id: 24, name: 'Clare Galambos-Winter Scholarships in Violin Performance', description: 'The purpose of these scholarships is to foster the performance careers of exceptionally talented musicians who have demonstrated a strong and clear commitment to a career in violin (or cello) performance. They are available at honours or undergraduate level.', grant_link: 'https://www.victoria.ac.nz/study/student-finance/scholarships/find-scholarship/scholarship-detail?detailCode=600542', conditions: '', amount: 0 }, // only for victoria uni
    { id: 25, name: 'Marie DAlbini Scholarship', description: 'For the founding and carrying on of a musical and vocal Scholarship.', grant_link: 'https://www.victoria.ac.nz/study/student-finance/scholarships/find-scholarship/scholarship-detail?detailCode=100192', conditions: '', amount: 0 }, // only victoria uni
    { id: 26, name: 'Ngarimu VC & 28TH (Maori) Battalion Memorial Scholarship Fund', description: 'For undergraduate NZ Maori applicant must be able to  show the link between Maori and the benefit of their study. Applicant must describe contribution to whanau, hapu or iwi following successful completion of their study.', grant_link: 'https://www.sit.ac.nz/Scholarships#311729-mori-scholarships', conditions: '', amount: 1000 }, // non specific to school
    // Sports specific grants
    { id: 27, name: 'Philip Ashton Smithells Memorial Scholarship', description: 'For a student progressing to their third or fourth year in Physical Education.', grant_link: 'https://www.otago.ac.nz/study/scholarships/database/otago014657.html', conditions: '', amount: 3000 },
    { id: 28, name: 'Philippa Sweetman Scholarship ', description: 'For a student going into or in their third or final year of a University of Otago Bachelors degree majoring in one of the principal disciplines of the former Home Science/Consumer and Applied Science Programme i.e Human Nutrition.', grant_link: 'https://www.otago.ac.nz/study/scholarships/database/otago014658.html', conditions: '', amount: 850 },
    { id: 29, name: 'Bee Nilson Award', description: 'Funds to support final year honours or paper year masters students studying human nutrition and food science.', grant_link: 'https://www.otago.ac.nz/study/scholarships/database/otago025487.html', conditions: '', amount: 6000 },
    // University of Auckland specific grants
    { id: 30, name: 'University of Auckland Māori Academic Excellence Scholarship', description: 'The main purpose of the scholarships is to recognise and reward exceptional academic performance combined with outstanding sporting, artistic, cultural and / or leadership achievements among Māori students.', grant_link: 'https://www.auckland.ac.nz/en/study/scholarships-and-awards/find-a-scholarship/university-of-auckland-maori-academic-excellence-scholarships-901-all.html', conditions: '', amount: 20000 },
    { id: 31, name: 'The University of Auckland Pacific Academic Excellence Scholarship', description: 'The main purpose of the Scholarships is to recognise and reward exceptional academic performance combined with outstanding sporting, artistic, cultural and / or leadership achievements among Pacific students. ', grant_link: 'https://www.auckland.ac.nz/en/study/scholarships-and-awards/find-a-scholarship/university-of-auckland-pacific-academic-excellence-scholarships-902-all.html', conditions: '', amount: 20000 },
    // Food specific grants
    { id: 32, name: 'Faculty of Science Entry Level Undergraduate Scholarship', description: 'The main purpose of the Scholarships is to encourage excellence in the study of subjects in the Faculty of Science and support students who reside outside the Auckland area.', grant_link: 'https://www.auckland.ac.nz/en/study/scholarships-and-awards/find-a-scholarship/faculty-of-science-entry-level-undergraduate-scholarships-622-sci.html', conditions: '', amount: 5000 }
    // // Dancing specific grants
    // { id: 300, name: '', description: '', grant_link: '', conditions: '', amount: 0 },
    // // Gadgets specific grants
    // { id: 300, name: '', description: '', grant_link: '', conditions: '', amount: 0 },
    // // Food specific grants
    // { id: 400, name: '', description: '', grant_link: '', conditions: '', amount: 0 }
    // // CHANGE ID NUMBERS!!
  ])
}
