exports.seed = (knex, Promise) => {
  return knex('location_study_junction').insert([
    // GAMING
    { id: 1, study_id: 1, location_id: 1 },
    { id: 2, study_id: 1, location_id: 7 },
    { id: 3, study_id: 1, location_id: 8 },
    { id: 4, study_id: 2, location_id: 1 },
    { id: 5, study_id: 3, location_id: 1 },
    { id: 6, study_id: 4, location_id: 1 },
    { id: 7, study_id: 5, location_id: 1 },
    { id: 8, study_id: 6, location_id: 1 },
    { id: 9, study_id: 7, location_id: 1 },
    { id: 10, study_id: 7, location_id: 7 },
    { id: 11, study_id: 8, location_id: 1 },
    { id: 12, study_id: 9, location_id: 7 },
    { id: 13, study_id: 10, location_id: 1 },
    // MUSIC
    { id: 14, study_id: 11, location_id: 13 },
    { id: 15, study_id: 12, location_id: 1 },
    { id: 16, study_id: 13, location_id: 1 },
    { id: 17, study_id: 14, location_id: 1 },
    { id: 18, study_id: 15, location_id: 7 },
    { id: 19, study_id: 16, location_id: 1 },
    { id: 20, study_id: 17, location_id: 1 },
    { id: 21, study_id: 18, location_id: 1 },
    { id: 22, study_id: 19, location_id: 5 },
    // SPORT
    { id: 23, study_id: 20, location_id: 1 },
    { id: 24, study_id: 21, location_id: 8 },
    { id: 25, study_id: 22, location_id: 1 },
    { id: 26, study_id: 23, location_id: 13 },
    { id: 27, study_id: 24, location_id: 1 },
    { id: 28, study_id: 25, location_id: 1 },
    { id: 29, study_id: 26, location_id: 1 },
    { id: 30, study_id: 27, location_id: 8 },
    { id: 31, study_id: 28, location_id: 1 },
    // // GADGETS
    { id: 32, study_id: 29, location_id: 1 },
    { id: 33, study_id: 30, location_id: 1 },
    { id: 34, study_id: 31, location_id: 1 },
    { id: 35, study_id: 32, location_id: 7 },
    { id: 36, study_id: 33, location_id: 1 },
    { id: 37, study_id: 34, location_id: 1 },
    { id: 38, study_id: 35, location_id: 1 },
    { id: 39, study_id: 36, location_id: 1 },
    { id: 40, study_id: 37, location_id: 1 },
    // DANCING
    { id: 41, study_id: 38, location_id: 1 },
    { id: 42, study_id: 39, location_id: 13 },
    { id: 43, study_id: 40, location_id: 7 },
    { id: 44, study_id: 41, location_id: 1 },
    { id: 45, study_id: 42, location_id: 1 },
    { id: 46, study_id: 43, location_id: 1 },
    { id: 47, study_id: 44, location_id: 1 },
    { id: 48, study_id: 45, location_id: 1 },
    { id: 49, study_id: 46, location_id: 7 },
    // FOOD
    { id: 50, study_id: 47, location_id: 1 },
    { id: 51, study_id: 48, location_id: 1 },
    { id: 52, study_id: 48, location_id: 7 },
    { id: 53, study_id: 48, location_id: 8 },
    { id: 54, study_id: 49, location_id: 1 },
    { id: 55, study_id: 50, location_id: 1 },
    { id: 56, study_id: 51, location_id: 1 },
    { id: 57, study_id: 51, location_id: 7 },
    { id: 58, study_id: 51, location_id: 8 },
    { id: 59, study_id: 52, location_id: 1 },
    { id: 60, study_id: 53, location_id: 1 },
    { id: 61, study_id: 54, location_id: 8 },
    { id: 62, study_id: 55, location_id: 8 }
  ])
}
