
exports.seed = function (knex, Promise) {
  return knex('grants').del()
    .then(function () {
      return knex('grants').insert([
        {id: 1, name: 'Norman Kirk Memorial Scholarship', description: 'Available to full-time Māori undergraduate students studying at a recognised New Zealand tertiary institute.', link: 'http://maorieducation.org.nz/undergraduate-scholarships-for-maori/', conditions: 'Condition 1', amount: 500},
        {id: 2, name: 'Pacific Education Foundation Scholarships (PEF)', description: 'Pacific Education Foundation (PEF) Scholarships are open to Pasifika students enrolled in tertiary study in New Zealand.', link: 'https://www.education.govt.nz/further-education/information-for-students/scholarships/pacific-education-foundation-scholarships-pef/', conditions: 'Condition 2', amount: 950},
        {id: 3, name: 'Rose Hellaby Bursaries Scholarship', description: 'Available to Māori undergraduate students studying in the scientific, mathematical or technical fields.', link: 'http://maorieducation.org.nz/undergraduate-scholarships-for-maori/', conditions: 'Condition 3', amount: 1000},
        {id: 4, name: 'Roy Watling Mitchell Bursaries Scholarship', description: 'Available to first-year Māori undergraduate students who attended secondary school as a Year 13 student in 2017.', link: 'http://maorieducation.org.nz/undergraduate-scholarships-for-maori/', conditions: 'Condition 4', amount: 1000},
        {id: 5, name: 'Sir Apirana Ngata Memorial Scholarship', description: 'Available to a full-time Māori undergraduate student studying at a recognised New Zealand tertiary institute, who attended Ngata Memorial College as a Year 13 student in 2017.', link: 'http://maorieducation.org.nz/undergraduate-scholarships-for-maori/', conditions: 'Condition 5', amount: 1000},
        {id: 6, name: 'Sister Annie Henry Scholarship', description: 'The Sister Annie Henry Trust was established in 1972 to assist in the education or training of any direct descendants of Reverend John Laughton, or students of Tūhoe descent.', link: 'http://maorieducation.org.nz/undergraduate-scholarships-for-maori/', conditions: 'Condition 6', amount: 700},
        {id: 7, name: 'Tī Maru Māori Trust Scholarship', description: 'Available to full-time Māori undergraduate students enrolled in their final year of study at a recognised New Zealand tertiary institute.', link: 'http://maorieducation.org.nz/undergraduate-scholarships-for-maori/', conditions: 'Condition 7', amount: 5000},
        {id: 8, name: 'Ngārimu VC and 28th (Māori) Battalion Memorial Scholarships', description: 'The Ngārimu VC and 28th (Māori) Battalion Memorial Scholarship Fund Board is looking for exceptional applicants of Māori descent who are undertaking tertiary study in 2018 and who possess characteristics that are considered consistent with those of the members of the 28th Māori Battalion.', link: 'http://www.education.govt.nz/further-education/information-for-students/scholarships/ngarimu-vc-and-28th-maori-battalion-memorial-scholarships/', conditions: 'Condition 8', amount: 10000},
        {id: 9, name: 'Māori Emerging Talent Scholarship', description: 'These scholarships will cover the tuition fees for the entire Digital Creativity foundation programme, which cover the fees for both the New Zealand Certificate in Arts and Design and the New Zealand Certificate in Digital Media and Design (that, combined, make up the Digital Creativity foundation programme).', link: 'https://www.mediadesignschool.com/scholarships/m%C4%81ori-emerging-talent-scholarship', conditions: 'Condition 9', amount: 9000},
        {id: 10, name: 'Pacific Emerging Talent Scholarship', description: 'These scholarships will cover the tuition fees for the entire Digital Creativity foundation programme, which cover the fees for both the New Zealand Certificate in Arts and Design and the New Zealand Certificate in Digital Media and Design (that, combined, make up the Digital Creativity foundation programme).', link: 'https://www.mediadesignschool.com/scholarships/pacific-emerging-talent-scholarship', conditions: 'Condition 10', amount: 9000},
        {id: 11, name: 'Girls in Games scholarship', description: 'The Girls in Games scholarship will give one female Game Artist and one female Game Programmer $2,000 to put towards their first year of undergraduate tuition fees at Media Design School.', link: 'https://www.mediadesignschool.com/scholarships/girls-in-games', conditions: 'Condition 11', amount: 2000},
        {id: 12, name: 'Unity Games Scholarship', description: 'This scholarship will offer one aspiring developer the opportunity to study game development with the number one ranked 3D animation, visual effects and game school in the Asia Pacific region by contributing $2000 towards their first year of tuition.', link: 'https://www.mediadesignschool.com/scholarships/unity-games-scholarship', conditions: 'Condition 12', amount: 2000},
        {id: 13, name: 'Academic Excellence Scholarship', description: 'This Academic Excellence Scholarship will give a student with exceptional academic potential in digital design $2,000 to put towards their first year of undergraduate degree-level tuition fees with the Media Design School.', link: 'https://www.mediadesignschool.com/scholarships/academic-excellence-scholarships', conditions: 'Condition 13', amount: 2000},
        {id: 14, name: 'Māori Academic Excellence Scholarships', description: 'The Māori Academic Excellence scholarships provide a Maori student with exceptional academic potential in digital design a 50% discount on year 1 and 50% discount on year 2 the tuition fees of their chosen programme of study at the Media Design School.', link: 'https://www.mediadesignschool.com/scholarships/m%C4%81ori-academic-excellence-scholarships', conditions: 'Condition 14', amount: 1},
        {id: 15, name: 'Pacific Academic Excellence Scholarship', description: 'The Pacific Academic Excellence scholarships provide a Pacifica student with exceptional academic potential in digital design a 50% discount on year 1 and 50% discount on year 2 the tuition fees of their chosen programme of study at the Media Design School.', link: 'https://www.mediadesignschool.com/scholarships/pacific-academic-excellence-scholarships', conditions: 'Condition 15', amount: 1},
        {id: 16, name: 'Te Uru Rangi', description: 'In conjunction with Te Puni Kōkiri and MBIE, Dev Academy is proud to announce 42 scholarships for Māori students. ', link: 'https://devacademy.co.nz/te-uru-rangi/', conditions: 'Condition 16', amount: 7000},
        {id: 17, name: 'Diversity Scholarship', description: 'This $500 scholarship is for people under-represented in the technology workforce, including anyone who belongs to an ethnic group under-represented in tech (e.g. Māori, Samoan, Tongan)', link: 'https://devacademy.co.nz/course-details/', conditions: 'Condition 17', amount: 500},
        {id: 18, name: 'AUT Kiwa Undergraduate Scholarships (Māori and Pacific Students)', description: '', link: 'https://www.aut.ac.nz/study-at-aut/fees-scholarships-and-finance/scholarships/scholarships-and-awards/detailpage?detailCode=501059&sessionID=3480429&sourceIP=&X_FORWARDED_FOR=', conditions: 'Condition 18', amount: 6500},
        {id: 19, name: 'AUT New Horizons Scholarships (Decile 1 – 4 Auckland Region Schools)', description: '', link: 'https://www.aut.ac.nz/study-at-aut/fees-scholarships-and-finance/scholarships/scholarships-and-awards/detailpage?detailCode=501060&sessionID=3480386&sourceIP=&X_FORWARDED_FOR=', conditions: 'Condition 19', amount: 6500},
        {id: 20, name: 'Maori Education Trust: Frances Irwin Hunt Art Scholarships', description: '', link: 'https://www.aut.ac.nz/study-at-aut/fees-scholarships-and-finance/scholarships/scholarships-and-awards/detailpage?detailCode=804031&sessionID=26622934&sourceIP=&X_FORWARDED_FOR=', conditions: 'Condition 20', amount: 3500},
        {id: 21, name: 'Maori Education Trust: Roy Watling Mitchell Prestigious Professions Scholarship', description: '', link: 'https://www.aut.ac.nz/study-at-aut/fees-scholarships-and-finance/scholarships/scholarships-and-awards/detailpage?detailCode=800342&sessionID=26622934&sourceIP=&X_FORWARDED_FOR=', conditions: 'Condition 21', amount: 5000},
        {id: 22, name: 'Te Herenga Waka Marae Whānau House Scholarship', description: 'The purpose of this scholarship is to encourage first year Māori students to academically and culturally achieve at Victoria University of Wellington.', link: 'https://www.victoria.ac.nz/explore/study-areas/music/study?subject=sonic-arts-and-music-technology', conditions: '', amount: 7698},
        {id: 23, name: 'New Zealand Pacific Scholarships', description: 'The New Zealand Pacific Scholarship recognises the very close personal, cultural and economic ties that New Zealand enjoys with Pacific countries. A particular focus of the scheme is to increase the number of young students and high academic achievers studying in New Zealand and to build a new generation of Pacific Leadership with strong links to New Zealand.', link: 'https://www.victoria.ac.nz/study/student-finance/scholarships/find-scholarship/scholarship-detail?detailCode=803308', conditions: '', amount: 1}
      ])
    })
}
